Repository nathanheinzmann/cg, pull requests merged in 2021-03, with the labels that each got.

#1 melhorias no helper.md e padrao de codigo
  .editorconfig
  helper.md
Labels: enhancement

#2 Gabao
  build_and_run.bash
  helper.md
Labels: insane stonks feature 🔥

#4 Nathan
  build_and_run.bash
  como compilar.txt
  exemplo03/exemplo03.c++
Labels: features

#5 Gabao
  Intro.md
  build_and_run.bash
  exemplo01/exemplo01.c++
  exemplo02/exemplo02.c++
  exemplo02/questoes.md
  exemplo03/exemplo03.c++
Labels: insane stonks feature 🔥
